setwd("~/Análisis de Tesis en Rstudio y SAGA GIS/Variables/Humedad/SSM_Bir  2020/1_Enero")
library(raster)
s <- stack(list.files(pattern = ".nc"), varname="ssm")
library(maps)
plot(extent(s))
maps::map("world", add =TRUE)
A <- stack(crop(s, drawExtent())
df <- as.data.frame(A, xy=TRUE)
saveRDS(df, file='Aragon.rds')
plot(A)
semana1_na_true <- calc(A[[1:7]], mean, na.rm=TRUE)
semana1_na_false <- calc(A[[1:7]], mean, na.rm=FALSE)
plot(semana1_na_true)
plot(semana1_na_false)
